version: '3'
services:
  t2iapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: text2image/search
    ports:
      - "8501:8501"
    environment:
      - QDRANT_URL=qdrant
      - QDRANT_COLLECTION=advert_captions
    volumes:
      - ./data/ads/images:/app/data/ads/images
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
